# Generated by Django 5.2.6 on 2025-10-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=255)),
                ('data_arquivo', models.DateField()),
                ('arquivo', models.FileField(upload_to='arquivos/')),
            ],
        ),
    ]
